language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm run test
- npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: rafalnowosielski@me.com
  api_key:
    secure: lCBUrHM8yn2hUfZIni1kkepNi+UOMbNiTZsnIK2LBoaHTMmUOk2t8b/wdjiy+wwck6GgBIdlQmZ2Q5S3YIVknrGQlABxj86y5pSQxyyuDeCvdbpR/GjH6UNnSLxpePBLo+B7Gixu963huC8vo44EWHXjYibUbzjdEau5FPuQI7jKT6PIQeDFlCatEDFUNb+eoyvdS7IUFUEOH/qBtFubVQ/d0cwwcjhama00ohFYieZVdiqhaWAqmfMRLmDbbO0F6nF3vj+U7Wofe7Kfxt3D5xXZu45oIRdseL9K+3rnwEZjbY2N0TAOoqNI5o/Oc1i3g9KPdV5aGJfRhmnBqHENn2eP+4FuKNcD5hvYkCAxI1PQGRGnu0bd8ja8jxv9UwXBNgd49NDJCXrA6OW3RxdzkIbkhrZKcq4L953Wrzn2CxSlHrM4/o2vgDxTFszEmfB2JVPtqlowNomIH0UFJdFsrZs53Ikw/l9n5NZ8YdURK66I7U8IE3lg6RntJVZP/cq1D0XfaxkyDLCCdVQQDhRsL23bCq1nPyyWgPcLXPEW0QJaDbSD+UmlX45lt0Rlna/n5dxglGIHRLL5vVuL7T/Q6XKEQZhAYmXBFMZfC3mICj7C9HLUAWhg9ZcNzIxKfvU4CI1U2RQQ1xY/ri7J8GwiwBb1FA//rXQwo+rHTL0Ke/c=
  on:
    branch: master
notifications:
  slack:
    secure: h/gAFbJ2QTRZZVG3q31eXqsyw+g/q/kIUKSYc58WyuERHE1/7nmMetkN9ThV2ibId7/CocDedtmzfG+J624KJweSZ5eT1a4AVBXq794R9/21duSVCdp64iTrPR0KBHePmbUs0jHpLvs2smjf2oJbfBqretWs4W1unJXQHxmg+U7+riCybTegzFTxmKbu6fnN810YySJLL+6Pdamb1qntwrW9rL7NlJhCUB+uFmN0I6R76rCOzlzjRdGAZ8Kc9oOfpDVaz8oosfGRaXifDI/w7VEteQWgW3j0X9FGH/UFF2p70Bys2XFDGJ0URScNiYNOB31hWXavUZc9ZlIk+NEmvY8rm+j6dqb6bCX56zT59DHd/trvZMo7ZaLqo5ZxcrVMjI8S/vEiCshvu4xpV0S3AB6cpd6sRXeJy9Jp2SRs4DVDyo5DOuhwZna59wHHPjxCrKKU7Ts51NezMk8IiSZM1KAjB8vLYFp7Ci8DvhccCkWRb0QBMprAqXH2qckc4OM6TC3Et4dvUSvI+cvni1pdDJxHHc4PNHlZ1e/sWjfozjt0sXXvdOJBlqqXUeVX44XiyldSG+Xqa8SmXyKRMG8PEBLAbC7/xNEnGnCpkn2Dpzjft58UJ8f7ij6AX1/5bxvXJquBfPbUul4cV0igc1WXP+Jz7U8R9gcq2I1GXquT/Ls=
